SHOW WAREHOUSES;

CREATE WAREHOUSE demo_warehouse
WITH
WAREHOUSE_SIZE = "X-small"
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = "For demo purpose";

SHOW WAREHOUSES;

ALTER WAREHOUSE DEMO_WAREHOUSE
SET MAX_CLUSTER_COUNT = 3;

SHOW WAREHOUSES;